"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config
from celery.schedules import crontab
from dotenv import load_dotenv
from redis import Redis

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



load_dotenv(os.path.join(BASE_DIR, '.env'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(' ')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # libs
    'drf_yasg',
    'drf_spectacular',
    'drf_spectacular_sidecar', 
    'django_filters',
    'rest_framework',
    'phonenumber_field',
    "corsheaders",
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'django_celery_beat',

    # apps
    'user',
    'catalog',
    'order'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=31),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',)
}



SPECTACULAR_SETTINGS = {
    'TITLE': 'IsmirKurulush API',
    'VERSION': '1.0.0',
}
# SPECTACULAR_SETTINGS = {
#     'TITLE': 'API',
#     'DESCRIPTION': '...',
#     'VERSION': '1.0.0',
#     'SECURITY': [
#         {'SessionAuth': []},   # <--- главное
#     ],
#     'AUTHENTICATION_WHITELIST': [],
#     'APPEND_COMPONENTS': {
#         "securitySchemes": {
#             "SessionAuth": {
#                 "type": "apiKey",
#                 "in": "header",
#                 "name": "X-Session-ID",   # <-- имя заголовка, которое будет в Swagger
#             }
#         }
#     },
# }

# SWAGGER_SETTINGS = {
#     # Класс авто-схемы, который мы реализуем ниже
#     'DEFAULT_AUTO_SCHEMA_CLASS': 'order.docs.custom_schema.CustomAutoSchema',
#     'USE_SESSION_AUTH': False,
#     # Добавляем security definition — это позволит вводить X-Session-Id через "Authorize" (опционально)
#     'SECURITY_DEFINITIONS': {
#         'SessionId': {
#             'type': 'apiKey',
#             'name': 'X-Session-Id',
#             'in': 'header'
#         }
#     },
#     # Если вы используете JWT:
#     'SECURITY_DEFINITIONS': {
#         'Bearer': {
#             'type': 'apiKey',
#             'name': 'Authorization',
#             'in': 'header'
#         },
#         'SessionId': {
#             'type': 'apiKey',
#             'name': 'X-Session-Id',
#             'in': 'header'
#         }
#     },
# }

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

REDIS_ANALYTICS_URL = os.getenv("REDIS_ANALYTICS_URL", "redis://localhost:6379/1")

CELERY_BEAT_SCHEDULE = {
    "sync-product-views-every-5-minutes": {
        "task": "catalog.tasks.sync_product_views",
        "schedule": timedelta(minutes=5),
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool)




REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL", "redis://localhost:6379/2")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "TIMEOUT": 60 * 5,  # 5 minutes
    },
    "analytics": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_ANALYTICS_URL,
    }
}


redis_default = Redis.from_url(CELERY_BROKER_URL)
redis_analytics = Redis.from_url(REDIS_ANALYTICS_URL)
redis_cache = Redis.from_url(REDIS_CACHE_URL)


AUTH_USER_MODEL = 'user.User'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

USE_X_FORWARDED_HOST = True

SITE_DOMAIN = os.getenv('SITE_DOMAIN', "https://ismir-kurulush-backend.com.kg")

SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'

CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'

SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost:3000",
    'http://34.70.155.154:80',
    'https://34.70.155.154:80',
    'http://34.70.155.154:443',
    'https://34.70.155.154:443',
    'http://34.70.155.154:8000',
    'http://localhost:8000',
    'http://0:0:0:0:8000',
    'http://172.18.0.1:8001',
    'https://localhost:8000',
    'https://0:0:0:0:8000',
    'https://172.18.0.1:8001',
    'http://flagman-backend.com.kg',
    'https://flagman-backend.com.kg',
    'http://www.flagman-backend.com.kg',
    'https://www.flagman-backend.com.kg',
    'http://localhost:8081',
    'http://0:0:0:0:8081',
    'http://172.18.0.1:8081',
    'http://172.17.0.1:8081',
    'https://localhost:8081',
    'https://0:0:0:0:8081',
    'https://172.18.0.1:8081',
    'https://172.17.0.1:8081',
    'http://10.0.2.2:8081',
    'https://10.0.2.2:8081',
    'http://34.70.155.154',
    'https://34.70.155.154',
]

CORS_ALLOW_METHODS = ['GET', 'OPTIONS', 'POST', 'PATCH', 'PUT', 'DELETE']

CORS_ALLOW_HEADERS = [
    'Accept',
    'Accept-Encoding',
    'Authorization',
    'Content-Type',
    'DNT',
    'Origin',
    'User-Agent',
    'X-CSRFToken',
    'X-Requested-With',
]

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True